### ISSUE TITLE
Not receiving Data From Amplifier

### ISSUE THREAD

**Issue by ikirtivardhansingh** [labstreaminglayer/liblsl-Python#49] opened 2021-11-18 09:18 UTC
Started ReceiveAndPlot.py but can't get any stream from the ANT EEGO.

**Comment by agricolab** [comment] 2021-11-18 19:13
How are you using to sending data via LSL from ANT eego? The sdk-app or their eego software? Can you verify it is actually sending?  What operating system are you using? Are you on the same machine as the Outlet? Is it an issue with the Outlet not being found or within ReceiveAndPlot.py?

It might be a network connectivity issue, see https://labstreaminglayer.readthedocs.io/info/network-connectivity.html

But we would need more information to answer this question better.

**Comment by madhavgovindgmg** [comment] 2021-11-22 09:50
> We were unable to installing the EEGO SDK on a Linux system so we were trying to directly read data from the device through the python code given in your repo.
> Currently we are using Ubuntu on a CPU powered by Intel i7 processor.
> Yes we are on the same machine as the outlet.

**Comment by agricolab** [comment] 2021-11-22 10:00
What makes you believe you could access the data from the device without the SDK and a corresponding streaming outlet? 

Afaik eemagine / Ant Neuro does not offer the SDK for Linux, and that means there are no drivers. Short of back-engineering, e.g. by listening to the traffic, or asking Ant Neuro whether they share the protocol with you, there isn't much i think one can do to run their amplifiers on linux. Probably easiest to switch to Windows. Didn't they sell you a Windows PC with the Amps? They usually do.

**Comment by madhavgovindgmg** [comment] 2021-11-22 10:54
Hey, Can I switch to Neuro electric??
I guess you would be the right person who can guide me here....
Does Neuro Electric have support for Linux??    
Also, Can I use it on a raspberry pi??

**Comment by agricolab** [comment] 2021-11-22 11:41
This discussion is already out of scope of this issue. Considering the issue was caused by a faulty setup with missing SDK,  i recommend you close it. 

If you need amplifiers that are supported on Linux, best you give manufactures a call, and ask them directly.

**Closed** 2021-11-22 14:26 UTC
